external_data_path: data/external/records.csv
gaode_key: 1a16f0704df05187cb6471f09e308cf8
gaode_base_url: https://restapi.amap.com
gaode_timeout: 10
public_ip_sources:
  - https://ipv4.icanhazip.com
public_ip_timeout: 3